# Generated by Django 6.0.2 on 2026-03-05 16:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('letterboxd_uri', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('movie_vector_store_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True, max_length=500, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('letterboxd_username', models.CharField(blank=True, max_length=64, null=True)),
                ('manual_import_count', models.PositiveIntegerField(default=0)),
                ('rss_import_count', models.PositiveIntegerField(default=0)),
                ('taste_vector_store_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'CSV'), ('rss', 'RSS')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movies_created', models.IntegerField(default=0)),
                ('movies_matched', models.IntegerField(default=0)),
                ('rel_created', models.IntegerField(default=0)),
                ('rel_updated', models.IntegerField(default=0)),
                ('had_reviews', models.BooleanField(default=False)),
                ('had_watchlist', models.BooleanField(default=False)),
                ('had_films', models.BooleanField(default=False)),
                ('events_created', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilmBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('query_text', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_bank', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='api.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='uniq_reco_user_movie')],
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('movie', 'genre'), name='uniq_movie_genre')],
            },
        ),
        migrations.CreateModel(
            name='MovieUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('watch_status', models.CharField(choices=[('Watched', 'Watched'), ('Want to Watch', 'Want to Watch'), ('Not Interested', 'Not Interested')], default='Watched', max_length=50)),
                ('watched_date', models.DateField(blank=True, null=True)),
                ('liked', models.BooleanField(default=False)),
                ('in_watchlist', models.BooleanField(default=False)),
                ('rewatch', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='api.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'watch_status', 'watched_date'], name='api_movieus_user_id_e04a8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('movie', 'user'), name='uniq_user_movie')],
            },
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=64, null=True)),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('movie', 'person', 'job'), name='uniq_movie_crew_role')],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=64, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('movie', 'person'), name='uniq_movie_cast')],
            },
        ),
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('rss', 'RSS'), ('csv', 'CSV'), ('manual', 'MANUAL')], default='rss', max_length=10)),
                ('posted_date', models.DateField(db_index=True)),
                ('entry_url', models.URLField(blank=True, db_index=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_key', models.CharField(db_index=True, max_length=40)),
                ('rewatch', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event_key'), name='unique_watch_event_user_event_key')],
            },
        ),
    ]
