# Generated by Django 6.0.2 on 2026-03-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_skipped_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
