# Generated by Django 6.0.2 on 2026-03-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_importbatch_error_message_importbatch_films_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='enrichment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='enrichment_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('enriching', 'Enriching'), ('done', 'Done'), ('failed', 'Failed'), ('not_found', 'Not Found')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
