# Generated by Django 6.0.2 on 2026-03-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_movie_enrichment_attempts_movie_enrichment_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='tmdb_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='tmdb_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='tmdb_queued',
            field=models.IntegerField(default=0),
        ),
    ]
