# Generated by Django 6.0.2 on 2026-03-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_importbatch_tmdb_done_importbatch_tmdb_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='status',
            field=models.CharField(default='queued', max_length=20),
        ),
    ]
