# Generated by Django 6.0.2 on 2026-03-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='had_watched_file',
            field=models.BooleanField(default=False),
        ),
    ]
