# Generated by Django 6.0.2 on 2026-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_importbatch_had_watched_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecast',
            name='character',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
