# Generated by Django 6.0.2 on 2026-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_moviecast_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_manual_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_rss_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
