# Generated by Django 6.0.2 on 2026-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_last_manual_sync_user_last_rss_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_rss_account_switch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
