# Generated by Django 6.0.2 on 2026-04-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_last_rss_account_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmbank',
            name='feedback_rating',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filmbank',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filmbank',
            name='feedback_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='filmbank',
            name='feedback_watched',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
