# Generated by Django 6.0.2 on 2026-04-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_filmbank_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_taste_rebuild_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
