# Generated by Django 6.0.2 on 2026-04-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_last_taste_rebuild_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='watchevent',
            name='unique_watch_event_user_event_key',
        ),
        migrations.AddConstraint(
            model_name='watchevent',
            constraint=models.UniqueConstraint(fields=('user', 'movie', 'posted_date'), name='unique_watch_per_user_movie_date'),
        ),
        migrations.AddConstraint(
            model_name='watchevent',
            constraint=models.UniqueConstraint(fields=('user', 'event_key'), name='unique_watch_event_key'),
        ),
    ]
