# Generated by Django 6.0.2 on 2026-04-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_watchevent_unique_watch_event_user_event_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='collection_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
